apiVersion: v2
name: openproject
description: A Helm chart for running OpenProject via Kubernetes
type: application
version: 0.1.0
appVersion: "12.3.0"
dependencies:
  - name: postgresql
    repository: "https://charts.bitnami.com/bitnami"
    version: 11.9.11
  - name: memcached
    repository: "https://charts.bitnami.com/bitnami"
    version: 6.2.7
