# Default values for openproject.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  imageRegistry: ""
  imagePullSecrets: []

replicaCount: 1

image:
  registry: docker.io
  repository: openproject/community
  pullPolicy: Always
  tag: "12.3.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  ports: 
    http: 80

containerPorts:
  http: 8080

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  host: openproject.local    
  path: /
  pathType: Prefix
  tls: true
  ## @param ingress.tlsSecret The tls configuration for hostnames to be covered with this ingress record.
  ## tlsSecret:
  ## - hosts:
  ##     - openproject.local
  ##   secretName: openproject-local-tls
  tlsSecret: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# @section Database parameters
# @param postgresql.enabled Switch to enable or disable the PostgreSQL helm chart
# host openproject-postgresql.openproject.svc.cluster.local
postgresql:
  enabled: true
  auth:
    username: bn_openproject
    database: openproject
    password: "easyPassword"
    postgresPassword: foobar

# External PostgreSQL configuration
# Just if postgresql.enabled is false
externalDatabase:
  host: ""
  port: 5432
  user: bn_openproject
  database: openproject
  password: ""

memcached:
  auth:
    user: foobar
    password: baz

openproject:
  foo: bar
