# Default values for openproject.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: openproject/community
  pullPolicy: Always
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  ports: 
    http: 80

containerPorts:
  http: 8080

ingress:
  enabled: true
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: demo.openproject-dev.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# @section Database parameters
# @param postgresql.enabled Switch to enable or disable the PostgreSQL helm chart
# host openproject-postgresql.openproject.svc.cluster.local
postgresql:
  enabled: true
  auth:
    username: bn_openproject
    database: openproject
    password: "easyPassword"
    postgresPassword: foobar

# External PostgreSQL configuration
# Just if postgresql.enabled is false
externalDatabase:
  host: ""
  port: 5432
  user: bn_openproject
  database: openproject
  password: ""

memcached:
  auth:
    user: foobar
    password: baz

openproject:
  foo: bar
